name: Bug report
description: Something in Pocket IRC isn't working
labels: ["bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Pocket IRC version
