package com.pocketirc.app.notif

import android.app.NotificationChannel
import android.app.NotificationManager
import android.content.Context
import android.media.AudioAttributes
import android.net.Uri
import android.os.Build
import com.pocketirc.app.PocketIrcApp

/**
 * Helper for creating and removing user-defined notification channels.
 *
 * Channel ids are generated by [generateId] and are stable for the lifetime
 * of the channel. The user-facing [CustomAlertChannel.name] is stored
 * separately and is the value users type into /alert -c <name>.
 *
 * Once an Android NotificationChannel exists, the OS remembers any user
 * customizations to it (sound, importance, vibration, etc.) even across
 * delete-and-recreate cycles, so this manager intentionally does not try to
 * "update" an existing channel by deleting and recreating it.
 */
object CustomChannelsManager {

    /** Map a "silent/quiet/normal/loud" string to an Android importance constant. */
    fun importanceFor(name: String): Int = when (name.lowercase()) {
        "silent" -> NotificationManager.IMPORTANCE_MIN
        "quiet" -> NotificationManager.IMPORTANCE_LOW
        "loud" -> NotificationManager.IMPORTANCE_HIGH
        else -> NotificationManager.IMPORTANCE_DEFAULT
    }

    /** Generate a stable channel id for a new custom channel. */
    fun generateId(userName: String): String {
        val slug = userName.lowercase()
            .replace(Regex("[^a-z0-9]+"), "_")
            .trim('_')
            .ifBlank { "ch" }
        val ts = System.currentTimeMillis().toString(36)
        return "irc_user_custom_${slug}_$ts"
    }

    /**
     * Create the underlying Android NotificationChannel for [ch]. Idempotent
     * — if a channel with the same id already exists, this is a no-op (the
     * existing channel keeps its current sound/importance).
     */
    fun create(context: Context, ch: CustomAlertChannel) {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) return
        val nm = context.getSystemService(NotificationManager::class.java)
        if (nm.getNotificationChannel(ch.channelId) != null) return
        val channel = NotificationChannel(
            ch.channelId,
            "Pocket IRC: ${ch.name}",
            importanceFor(ch.importance),
        ).apply {
            enableVibration(ch.vibration)
            enableLights(ch.lights)
            setShowBadge(ch.badge)
            if (ch.sound.isNotBlank()) {
                val uri = runCatching { Uri.parse(ch.sound) }.getOrNull()
                if (uri != null) {
                    val attrs = AudioAttributes.Builder()
                        .setUsage(AudioAttributes.USAGE_NOTIFICATION)
                        .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                        .build()
                    setSound(uri, attrs)
                }
            }
        }
        nm.createNotificationChannel(channel)
    }

    /** Delete an Android NotificationChannel by id. */
    fun delete(context: Context, channelId: String) {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) return
        val nm = context.getSystemService(NotificationManager::class.java)
        nm.deleteNotificationChannel(channelId)
    }

    /**
     * Resolve a user-typed channel name (built-in or custom) to the actual
     * Android channel id used by the notification builder. Returns null if
     * the name doesn't match anything; callers should fall back to
     * [PocketIrcApp.CHANNEL_USER_NORMAL].
     */
    fun resolve(name: String?, customs: List<CustomAlertChannel>): String? {
        if (name.isNullOrBlank()) return null
        val n = name.lowercase()
        PocketIrcApp.USER_CHANNEL_NAMES[n]?.let { return it }
        return customs.firstOrNull { it.name.equals(n, ignoreCase = true) }?.channelId
    }
}
